//  --========================================================================--
//  This confidential and proprietary software may be used only as
//  authorised by a licensing agreement from ARM Limited
//     (C) COPYRIGHT 2003-2006 ARM Limited
//           ALL RIGHTS RESERVED
//  The entire notice above must be reproduced on all authorised
//  copies and copies may only be made to the extent permitted
//  by a licensing agreement from ARM Limited.
//
//  ----------------------------------------------------------------------------
//  Version and Release Control Information:
//
//  File Name           : AsyncAxiFifo8Rd.v,v
//  File Revision       : 1.4
//
//  Release Information : PL301-r1p1-00rel0
//
//  ----------------------------------------------------------------------------
//  Purpose             : Read logic of 8-deep FIFO for
//                        AXI to AXI asynchronous bridge with synchronous bypass
//
//  --========================================================================--


module AsyncAxiFifo8Rd
  (
   // Inputs
   CLK,
   RESETn,
   READY,
   WrPtrG,
   Reg0,
   Reg1,
   Reg2,
   Reg3,
   Reg4,
   Reg5,
   Reg6,
   Reg7,
   ByReq,
   VALIDBypass,
   DATABypass,
   // Outputs
   VALID,
   DATA,
   RdPtrG,
   ByAck,
   READYBypass
   );
   
   parameter               DATAWIDTH = 64;
   
   parameter               PTRRESET = 4'b1111;
   parameter               PTRWIDTH = 4;
   
   input                   CLK;         // AXI Clock
   input                   RESETn;      // AXI Reset
   input [DATAWIDTH-1:0]   Reg0;        // DATA bus from Reg0
   input [DATAWIDTH-1:0]   Reg1;        // DATA bus from Reg1
   input [DATAWIDTH-1:0]   Reg2;        // DATA bus from Reg2
   input [DATAWIDTH-1:0]   Reg3;        // DATA bus from Reg3
   input [DATAWIDTH-1:0]   Reg4;        // DATA bus from Reg0
   input [DATAWIDTH-1:0]   Reg5;        // DATA bus from Reg1
   input [DATAWIDTH-1:0]   Reg6;        // DATA bus from Reg2
   input [DATAWIDTH-1:0]   Reg7;        // DATA bus from Reg3
   input                   READY;       // READY handshake signal from FIFO
   input [PTRWIDTH-1:0]    WrPtrG;      // FIFO gray encoded Write pointer
   
   input                   ByReq;       // request to enter bypass mode
   input                   VALIDBypass; // VALID from upstream for bypass mode
   input [DATAWIDTH-1:0]   DATABypass;  // DATA from upstream for bypass mode
   
   output [DATAWIDTH-1:0]  DATA;        // DATA bus
   output                  VALID;       // VALID handshake signal
   output [PTRWIDTH-1:0]   RdPtrG;      // FIFO gray encoded Read pointer
   
   output                  ByAck;       // bypass mode acknowledgement
   output                  READYBypass; // READY for upstream for bypass mode
   
   
   
   //---------------------------------------------------------------------------
   // Constant declarations
   //---------------------------------------------------------------------------
   
   
   //---------------------------------------------------------------------------
   // Signal declarations
   //---------------------------------------------------------------------------
   // Registered signals
   
   reg                     ByReqSync;   // synchronised ByReq
   reg                     ByReqSync1;  // part synchronised ByReq
   reg                     iByAck;      // ack that we are in bypass
   reg [PTRWIDTH-1:0]      WrPtrGSync1; // part synchronised version of WrPtrG
   reg [PTRWIDTH-1:0]      WrPtrGSync;  // Synchronised version of WrPtrG
   reg [PTRWIDTH-1:0]      iRdPtrG;     // Internal version of Read Pointer
   reg [DATAWIDTH-1:0]     iDATA;       // DATA bus from data output latch
   
   // --------------------------------------------------------------------------
   //  Wire declarations
   // --------------------------------------------------------------------------
   
   wire                    iVALID;       // the VALID generated by the FIFO
   wire                    iREADY;       // FIFO's view of the downstream READY
   wire                    nFIFOEmpty;   // FIFO not empty status indicator
   wire                    Popdata;      // Pop data from FIFO
   wire [PTRWIDTH-1:0]     NextRdPtrG;   // D-input of the read pointer
   wire                    NextByAck;    // Next value of ByAck


   //---------------------------------------------------------------------------
   // Beginning of main code
   //---------------------------------------------------------------------------

   // --------------------------------------------------------------------------
   // BYPASS stuff
   // --------------------------------------------------------------------------

   // Synchronisation of ByReq
   always @(posedge CLK or negedge RESETn)
     begin : p_sync_ByReq
        if (RESETn == 1'b0)
          begin
             ByReqSync <= 1'b0;
             ByReqSync1 <= 1'b0;
          end
        else
          begin
             ByReqSync <= ByReqSync1;
             ByReqSync1 <= ByReq;
          end
     end // block: p_sync_ByReq

   // Generation of ByAck
   always @(posedge CLK or negedge RESETn)
     begin : p_gen_ByAck
        if (RESETn == 1'b0)
          iByAck <= 1'b0;
        else
          // If we have been asked to go into bypass and the FIFO is
          // empty then we can. Come out immediately
          iByAck <= NextByAck;
     end // block: p_sync_ByReq
   assign NextByAck = ByReqSync & ~nFIFOEmpty;

   // bypass signals
   assign DATA = iByAck ? DATABypass : iDATA ;
   assign READYBypass = iByAck ? READY : 1'b0;
   assign iREADY = ~ByReqSync & ~iByAck & READY;
   assign VALID = iByAck ? VALIDBypass : iVALID;
   
   assign ByAck = iByAck;
   
   // --------------------------------------------------------------------------
   // Synchronisation of WrPtrG
   // --------------------------------------------------------------------------
   
   always @(posedge CLK or negedge RESETn)
     begin : p_sync_WrPtrG
        if (RESETn == 1'b0)
          begin
             WrPtrGSync1  <= PTRRESET;
             WrPtrGSync   <= PTRRESET;
          end
        else
          begin
             WrPtrGSync1   <= WrPtrG;
             WrPtrGSync    <= WrPtrGSync1;
          end
     end // block: p_sync_WrPtrG
      
   
   // --------------------------------------------------------------------------
   // FIFO full and empty logic.
   // --------------------------------------------------------------------------
   
   assign nFIFOEmpty = (WrPtrGSync ==  iRdPtrG) ? 1'b0 : 1'b1;

   
   // --------------------------------------------------------------------------
   // Control of flow
   //
   // Assert iVALID whenever there is data in the FIFO
   // (i.e. nFIFOEmpty).  Deassert iVALID when data can move out of
   // the data register (i.e. READY), but there is no data from the
   // FIFO (i.e. !nFIFOEmpty), so the data register will be empty.
   // --------------------------------------------------------------------------

   assign iVALID = nFIFOEmpty;
           
   
   // --------------------------------------------------------------------------
   // Read Logic
   // --------------------------------------------------------------------------
   
   // --------------------------------------------------------------------------
   // Reads from the FIFO when there is data there (nFIFOEmpty) and
   // either there is nothing in the data register (!iVALID) or
   // anything there will be disappearing (iREADY).  When we read, we
   // also update the read pointer
   // --------------------------------------------------------------------------
   
   assign Popdata = iREADY & nFIFOEmpty;
   
   // Update read pointer and output buffer
   always @(posedge CLK or negedge RESETn)
     begin : p_rdptr_seq
        if (RESETn == 1'b0)
          iRdPtrG   <= PTRRESET;
        else if (Popdata)
          iRdPtrG     <= NextRdPtrG;
     end
   
   AsyncAxiNxtGray8 uNextGray8
     (
      .Curr(iRdPtrG),
      .Nxt(NextRdPtrG)
      );
 

   // Read data into output buffer
   always@(iRdPtrG or Reg0 or Reg1 or Reg2 or Reg3 or Reg4 or Reg5 or Reg6 or Reg7)
     begin : p_rdata_mux
        case (iRdPtrG)
          4'b0000  : iDATA = Reg0;
          4'b0001  : iDATA = Reg1;
          4'b0011  : iDATA = Reg2;
          4'b0010  : iDATA = Reg3;
          4'b0110  : iDATA = Reg4;
          4'b0111  : iDATA = Reg5;
          4'b0101  : iDATA = Reg6;
          4'b0100  : iDATA = Reg7;
          4'b1100  : iDATA = Reg0;
          4'b1101  : iDATA = Reg1;
          4'b1111  : iDATA = Reg2;
          4'b1110  : iDATA = Reg3;
          4'b1010  : iDATA = Reg4;
          4'b1011  : iDATA = Reg5;
          4'b1001  : iDATA = Reg6;
          4'b1000  : iDATA = Reg7;
          default : iDATA = {DATAWIDTH{1'bx}};
        endcase
     end
   
   
   // --------------------------------------------------------------------------
   // Drive outputs with internal signals
   // --------------------------------------------------------------------------
   
   assign RdPtrG = iRdPtrG;
   

// synopsys translate_off
`ifdef ASSERT_ON
   //---------------------------------------------------------------------------
   // OVL Assertions
   //---------------------------------------------------------------------------
   
   //---------------------------------------------------------------------------
   // Check that iRdPtrG and NextRdPtrG differ by only one bit
   //---------------------------------------------------------------------------
   // OVL_ASSERT_RTL
   
   assert_one_hot #(0, PTRWIDTH, 0, 
                    "iRdPtrG and NextRdPtrG differ by more than one bit")
     ovlRdPtrOneHot 
       (
        .clk           (CLK),
        .reset_n       (RESETn),
        .test_expr     (iRdPtrG ^ NextRdPtrG)
        );
   
   // OVL_ASSERT_END

   //---------------------------------------------------------------------------
   // Check that NextRdPtrG does not go 'X'.
   //---------------------------------------------------------------------------
   // OVL_ASSERT_RTL
   
   assert_always #(0, 0, "X generation of NextRdPtrG")
     ovlNextRdPtrGX 
       (
        .clk           (CLK),
        .reset_n       (RESETn),
        .test_expr     (|(NextRdPtrG ^ NextRdPtrG) === 1'b0) // check for X
        );
   
   // OVL_ASSERT_END
   
   //---------------------------------------------------------------------------
   // Check that we do not underflow.
   //---------------------------------------------------------------------------
   // OVL_ASSERT_RTL
   
   assert_never #(0, 0, "Underflow - reading when all FIFO slots are empty")
     ovlUnderflow
       (
        .clk           (CLK),
        .reset_n       (RESETn),
        .test_expr     (iREADY & iVALID & ~nFIFOEmpty)
        );
   
   // OVL_ASSERT_END
   
`endif
// synopsys translate_on

endmodule  // AsyncAxiFifo4Rd

//  --=============================== End =================================--
