//  --========================================================================--
//  This confidential and proprietary software may be used only as
//  authorised by a licensing agreement from ARM Limited
//     (C) COPYRIGHT 2003-2006 ARM Limited
//           ALL RIGHTS RESERVED
//  The entire notice above must be reproduced on all authorised
//  copies and copies may only be made to the extent permitted
//  by a licensing agreement from ARM Limited.
//
//  ----------------------------------------------------------------------------
//  Version and Release Control Information:
//
//  File Name           : AsyncAxiFifo8Wr.v,v
//  File Revision       : 1.3
//
//  Release Information : PL301-r1p1-00rel0
//
//  ----------------------------------------------------------------------------
//  Purpose             : Write logic of 8-deep FIFO for
//                        AXI to AXI asynchronous bridge with synchronous bypass
//
//  --========================================================================--


module AsyncAxiFifo8Wr
  (
   // Inputs
   CLK,
   RESETn,
   VALID,
   DATA,
   RdPtrG,
   ByReq,
   READYBypass,
   // Outputs
   READY,
   WrPtrG,
   Reg0,
   Reg1,
   Reg2,
   Reg3,
   Reg4,
   Reg5,
   Reg6,
   Reg7,
   ByAck,
   VALIDBypass,
   DATABypass
   );
   
   parameter               DATAWIDTH = 64;

   parameter               PTRWIDTH = 4;
   parameter               PTRRESET = 4'b1111;
   parameter               FULLXORVAL = 4'b1100;
   
   input                   CLK;         // AXI Clock
   input                   RESETn;      // AXI Reset
   input                   VALID;       // VALID handshake signal
   input [DATAWIDTH-1:0]   DATA;        // DATA bus
   input [PTRWIDTH-1:0]    RdPtrG;      // FIFO gray encoded Read pointer

   input                   ByReq;       // request to enter bypass mode
   input                   READYBypass; // READY from downstream for bypass mode
   
   output                  READY;       // READY handshake signal from FIFO
   output [PTRWIDTH-1:0]   WrPtrG;      // FIFO gray encoded Write pointer
   output [DATAWIDTH-1:0]  Reg0;        // DATA bus from Reg0
   output [DATAWIDTH-1:0]  Reg1;        // DATA bus from Reg1
   output [DATAWIDTH-1:0]  Reg2;        // DATA bus from Reg2
   output [DATAWIDTH-1:0]  Reg3;        // DATA bus from Reg3
   output [DATAWIDTH-1:0]  Reg4;        // DATA bus from Reg4
   output [DATAWIDTH-1:0]  Reg5;        // DATA bus from Reg5
   output [DATAWIDTH-1:0]  Reg6;        // DATA bus from Reg6
   output [DATAWIDTH-1:0]  Reg7;        // DATA bus from Reg7
   
   output                  ByAck;       // acknowledge entering bypass mode
   output                  VALIDBypass; // VALID for downstream for bypass mode
   output [DATAWIDTH-1:0]  DATABypass;  // DATA for downstream for bypass mode
   
   //---------------------------------------------------------------------------
   // Constant declarations
   //---------------------------------------------------------------------------
   
   
   //---------------------------------------------------------------------------
   // Signal declarations
   //---------------------------------------------------------------------------
   // Registered output signals
   
   reg                     ByReqSync;   // synchronised ByReq
   reg                     ByReqSync1;  // part synchronised ByReq
   reg                     iByAck;      // ack that we are in bypass
   reg [PTRWIDTH-1:0]      RdPtrGSync;  // synchronised RdPtrG
   reg [PTRWIDTH-1:0]      RdPtrGSync1; // part synchronise RdPtrG
   reg [PTRWIDTH-1:0]      iWrPtrG;     // Write Pointer gray encoded
   reg [DATAWIDTH-1:0]     Reg0;        // FIFO - Address 0
   reg [DATAWIDTH-1:0]     Reg1;        // FIFO - Address 1
   reg [DATAWIDTH-1:0]     Reg2;        // FIFO - Address 2
   reg [DATAWIDTH-1:0]     Reg3;        // FIFO - Address 3
   reg [DATAWIDTH-1:0]     Reg4;        // FIFO - Address 4
   reg [DATAWIDTH-1:0]     Reg5;        // FIFO - Address 5
   reg [DATAWIDTH-1:0]     Reg6;        // FIFO - Address 6
   reg [DATAWIDTH-1:0]     Reg7;        // FIFO - Address 7
  
    
   // --------------------------------------------------------------------------
   //  Wire declarations
   // --------------------------------------------------------------------------

   wire                    FIFOEmpty;  // when the WrPtr and synchronised RdPtr
   wire                    iVALID;     // FIFO's view of the upstream VALID
   wire                    iREADY;     // the READY generated by the FIFO
   wire                    nFIFOFull;  // FIFO not full
   wire                    Pushdata;   // Puts data into FIFO
   wire [PTRWIDTH-1:0]     NextWrPtrG; // D-input of the write pointer
   wire                    EN0;        // Enable for FIFO0
   wire                    EN1;        // Enable for FIFO1
   wire                    EN2;        // Enable for FIFO2
   wire                    EN3;        // Enable for FIFO3
   wire                    EN4;        // Enable for FIFO4
   wire                    EN5;        // Enable for FIFO5
   wire                    EN6;        // Enable for FIFO6
   wire                    EN7;        // Enable for FIFO7
   wire                    NextByAck;  // Next value for ByAck

 
   //---------------------------------------------------------------------------
   // Beginning of main code
   //---------------------------------------------------------------------------
   
   // --------------------------------------------------------------------------
   // BYPASS stuff
   // --------------------------------------------------------------------------

   // Synchronisation of ByReq
   always @(posedge CLK or negedge RESETn)
     begin : p_sync_ByReq
        if (RESETn == 1'b0)
          begin
             ByReqSync <= 1'b0;
             ByReqSync1 <= 1'b0;
          end
        else
          begin
             ByReqSync <= ByReqSync1;
             ByReqSync1 <= ByReq;
          end
     end // block: p_sync_ByReq

   // Generation of ByAck
   // If we have been asked to go into bypass and the FIFO is
   // empty then we can. Come out when we are not in the
   // middle of a transaction.
   always @(posedge CLK or negedge RESETn)
     begin : p_gen_ByAck
        if (RESETn == 1'b0)
          iByAck <= 1'b0;
        else
          iByAck <= NextByAck;
     end // block: p_sync_ByReq
   assign NextByAck = (ByReqSync & FIFOEmpty) | (iByAck & VALID & ~READYBypass);

   // bypass signals
   assign DATABypass = DATA;
   assign VALIDBypass = iByAck & VALID;
   assign iVALID = ~ByReqSync & ~iByAck & VALID;
   assign READY = iByAck ? READYBypass : (iREADY & ~ByReqSync);
   
   assign ByAck = iByAck;
   
   // --------------------------------------------------------------------------
   // Synchronisation of RdPtrG
   // --------------------------------------------------------------------------
   
   always @(posedge CLK or negedge RESETn)
     begin : p_sync_RdPtrG
        if (RESETn == 1'b0)
          begin
             RdPtrGSync   <= PTRRESET;
             RdPtrGSync1  <= PTRRESET;
          end
        else
          begin
             RdPtrGSync   <= RdPtrGSync1;
             RdPtrGSync1  <= RdPtrG;
          end
     end // block: p_sync_RdPtrG

   
   // --------------------------------------------------------------------------
   // FIFO full and empty logic.
   // --------------------------------------------------------------------------
   
   assign nFIFOFull = ((iWrPtrG ^ RdPtrGSync) != FULLXORVAL);
   assign FIFOEmpty = (iWrPtrG == RdPtrGSync);
   
   // --------------------------------------------------------------------------
   // Control of flow
   //
   // Assert iREADY when the FIFO is not full
   // --------------------------------------------------------------------------

   assign iREADY = nFIFOFull;
 
   // --------------------------------------------------------------------------
   // Write Logic
   // --------------------------------------------------------------------------
   
   // --------------------------------------------------------------------------
   // Write to the FIFO when VALID is asserted and we have space. When
   // we write, also increment the write pointer.
   // --------------------------------------------------------------------------
   
   assign Pushdata = iVALID & nFIFOFull;
   
   // Update the write pointer
   always @(posedge CLK or negedge RESETn)
     begin : p_wrptr_seq
        if (RESETn == 1'b0)
          iWrPtrG    <= PTRRESET;
        else if (Pushdata)
          iWrPtrG    <= NextWrPtrG;
     end // block: p_wrptr_seq
   
   AsyncAxiNxtGray8 uNextGray8
     (
      .Curr(iWrPtrG),
      .Nxt(NextWrPtrG)
      );
   
   // Generate Data enables for each FIFO
   assign EN0 = Pushdata & ((iWrPtrG == 4'b0000) || (iWrPtrG == 4'b1100));
   assign EN1 = Pushdata & ((iWrPtrG == 4'b0001) || (iWrPtrG == 4'b1101));
   assign EN2 = Pushdata & ((iWrPtrG == 4'b0011) || (iWrPtrG == 4'b1111));
   assign EN3 = Pushdata & ((iWrPtrG == 4'b0010) || (iWrPtrG == 4'b1110));
   assign EN4 = Pushdata & ((iWrPtrG == 4'b0110) || (iWrPtrG == 4'b1010));
   assign EN5 = Pushdata & ((iWrPtrG == 4'b0111) || (iWrPtrG == 4'b1011));
   assign EN6 = Pushdata & ((iWrPtrG == 4'b0101) || (iWrPtrG == 4'b1001));
   assign EN7 = Pushdata & ((iWrPtrG == 4'b0100) || (iWrPtrG == 4'b1000));

   // Write data0
   always @(posedge CLK or negedge RESETn)
     begin : p_wr_reg0
        if (RESETn == 1'b0)
          begin
             Reg0 <= {DATAWIDTH{1'b0}};
          end
        else if (EN0)
          begin
             Reg0 <= DATA;
          end
     end

   // Write data1
   always @(posedge CLK or negedge RESETn)
     begin : p_wr_reg1
        if (RESETn == 1'b0)
          begin
             Reg1 <= {DATAWIDTH{1'b0}};
          end
        else if (EN1)
          begin
             Reg1 <= DATA;
          end
     end

   // Write data2
   always @(posedge CLK or negedge RESETn)
     begin : p_wr_reg2
        if (RESETn == 1'b0)
          begin
             Reg2 <= {DATAWIDTH{1'b0}};
          end
        else if (EN2)
          begin
             Reg2 <= DATA;
          end
     end

   // Write data3
    always @(posedge CLK or negedge RESETn)
     begin : p_wr_reg3
        if (RESETn == 1'b0)
          begin
             Reg3 <= {DATAWIDTH{1'b0}};
          end
        else if (EN3)
          begin
             Reg3 <= DATA;
          end
     end
   
   // Write data4
    always @(posedge CLK or negedge RESETn)
     begin : p_wr_reg4
        if (RESETn == 1'b0)
          begin
             Reg4 <= {DATAWIDTH{1'b0}};
          end
        else if (EN4)
          begin
             Reg4 <= DATA;
          end
     end
   
   // Write data5
    always @(posedge CLK or negedge RESETn)
     begin : p_wr_reg5
        if (RESETn == 1'b0)
          begin
             Reg5 <= {DATAWIDTH{1'b0}};
          end
        else if (EN5)
          begin
             Reg5 <= DATA;
          end
     end
   
   // Write data6
    always @(posedge CLK or negedge RESETn)
     begin : p_wr_reg6
        if (RESETn == 1'b0)
          begin
             Reg6 <= {DATAWIDTH{1'b0}};
          end
        else if (EN6)
          begin
             Reg6 <= DATA;
          end
     end
   
   // Write data7
    always @(posedge CLK or negedge RESETn)
     begin : p_wr_reg7
        if (RESETn == 1'b0)
          begin
             Reg7 <= {DATAWIDTH{1'b0}};
          end
        else if (EN7)
          begin
             Reg7 <= DATA;
          end
     end
   
  
   // --------------------------------------------------------------------------
   // Drive output with internal signal
   // --------------------------------------------------------------------------
   
   assign WrPtrG = iWrPtrG;

   
// synopsys translate_off
`ifdef ASSERT_ON
   //---------------------------------------------------------------------------
   // OVL Assertions
   //---------------------------------------------------------------------------
   
   //---------------------------------------------------------------------------
   // Check that iWrPtrG and NextWrPtrG differ by only one bit
   //---------------------------------------------------------------------------
   // OVL_ASSERT_RTL
   
   assert_one_hot #(0, PTRWIDTH, 0, 
                    "iWrPtrG and NextWrPtrG differ by more than one bit")
     ovlWrPtrOneHot 
       (
        .clk           (CLK),
        .reset_n       (RESETn),
        .test_expr     (iWrPtrG ^ NextWrPtrG)
        );
   
   // OVL_ASSERT_END

   //---------------------------------------------------------------------------
   // Check that NextWrPtrG does not go 'X'.
   //---------------------------------------------------------------------------
   // OVL_ASSERT_RTL
   
   assert_always #(0, 0, "X generation of NextWrPtrG")
     ovlNextWrPtrGX 
       (
        .clk           (CLK),
        .reset_n       (RESETn),
        .test_expr     (|(NextWrPtrG ^ NextWrPtrG) === 1'b0) // check for X
        );
   
   // OVL_ASSERT_END
   
   //---------------------------------------------------------------------------
   // Check that we do not overflow.
   //---------------------------------------------------------------------------
   // OVL_ASSERT_RTL
   
   assert_never #(0, 0, "Overflow - writing when all FIFO slots are full")
     ovlOverflow
       (
        .clk           (CLK),
        .reset_n       (RESETn),
        .test_expr     (iREADY & iVALID & ~nFIFOFull)
        );
   
   // OVL_ASSERT_END
   
`endif
// synopsys translate_on

endmodule

//  --=============================== End =================================--