sim:
		$(MAKE) -C work sim TOP=$(TOP) MODE=$(MODE)

fpga_sim:
		$(MAKE) -C work fpga_sim TOP=$(TOP) MODE=$(MODE)

compile:
		$(MAKE) -C work compile TOP=$(TOP) MODE=$(MODE)

clean:
		$(MAKE) -C work clean

verdi:
		$(MAKE) -C work verdi TOP=$(TOP)

fpga_verdi:
		$(MAKE) -C work fpga_verdi TOP=$(TOP) MODE=$(MODE)

update:
		$(MAKE) -C work update

clean_memory:
		$(MAKE) -C work clean_memory