#!/usr/bin/perl
use strict; 
use Getopt::Long;

my $help = "";
my $file = "";
my $bitwidth = 1;
my $p = 64;

GetOptions(
  "file=s" => \$file, 
  "help" => \$help, 
  "bitwidth:s" => \$bitwidth, 
  "p:s" => \$p, 
) or die "Error in command line arguments\n";

if ($help) {
  print "Usage: perl pea.pl --file <file> --p <p> --lane <lane> --layer <layer> --ifmap_sram_depth <ifmap_sram_depth> --weight_sram_depth <weight_sram_depth> --psum_sram_depth <psum_sram_depth>\n";
  print "Options:\n";
  print "  --file <file>               Output file\n";
  print "  --bitwidth <bitwidth>       Bitwidth\n";
  print "  --p <p>                     parallelism\n";
  exit;
}

print "==== INFO: Generating selector ==== \n";
print "File: $file\n";
print "Bitwidth: $bitwidth\n";
print "p: $p\n";

my $fh;

if ($file eq "") {
  die "Error: file is not specified\n";
}
else {
  open $fh, ">" , $file or die "Can't open file: $!";
}

print $fh "module sparse_selector_" . $p . "_" . $bitwidth . "bit (\n";
print $fh "  mask,\n";
print $fh "  data,\n";
print $fh "  mode,\n";
print $fh "  out\n";
print $fh ");\n";
print $fh "\n";
print $fh "input [" . ($p * 8-1) . ":0] mask;\n";
print $fh "input [" . ($p * $bitwidth * 8 -1) . ":0] data;\n";
print $fh "input [3:0] mode;\n";
print $fh "output reg [" . ($p * $bitwidth - 1) . ":0] out;\n";
print $fh "\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_four_one;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_four_two;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_eight_one;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_eight_two;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_eight_four;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_sixteen_two;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_sixteen_four;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_sixteen_eight;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_thridtytwo_four;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_thridtytwo_eight;\n";
print $fh "wire [" . ($p * $bitwidth - 1) . ":0] result_thridtytwo_sixteen;\n";
print $fh "\n";
print $fh "genvar four_one_i;\n";
print $fh "generate\n";
print $fh "  for (four_one_i = 0; four_one_i < $p; four_one_i = four_one_i + 1) begin : four_one_mux\n";
print $fh "    mux_4to1_" . $bitwidth . "bit u_four_one_mux(\n";
print $fh "      .mask(mask[four_one_i*4 +: 4]),\n";
print $fh "      .data(data[four_one_i*" . $bitwidth * 4 . " +: " . $bitwidth * 4 . "]),\n";
print $fh "      .out(result_four_one[four_one_i*" . $bitwidth . " +: " . $bitwidth . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar four_two_i;\n";
print $fh "generate\n";
print $fh "  for (four_two_i = 0; four_two_i < ". int($p/2) ."; four_two_i = four_two_i + 1) begin : four_two_mux\n";
print $fh "    mux_4to2_" . $bitwidth . "bit u_four_two_mux(\n";
print $fh "      .mask(mask[four_two_i*4 +: 4]),\n";
print $fh "      .data(data[four_two_i*" . $bitwidth * 4 . " +: " . $bitwidth * 4 . "]),\n";
print $fh "      .out(result_four_two[four_two_i*" . $bitwidth * 2 . " +: " . $bitwidth * 2 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar eight_one_i;\n";
print $fh "generate\n";
print $fh "  for (eight_one_i = 0; eight_one_i < ". $p ."; eight_one_i = eight_one_i + 1) begin : eight_one_mux\n";
print $fh "    mux_8to1_" . $bitwidth . "bit u_eight_one_mux(\n";
print $fh "      .mask(mask[eight_one_i*8 +: 8]),\n";
print $fh "      .data(data[eight_one_i*" . $bitwidth * 8 . " +: " . $bitwidth * 8 . "]),\n";
print $fh "      .out(result_eight_one[eight_one_i*" . $bitwidth . " +: " . $bitwidth . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar eight_two_i;\n";
print $fh "generate\n";
print $fh "  for (eight_two_i = 0; eight_two_i < ". int($p/2) ."; eight_two_i = eight_two_i + 1) begin : eight_two_mux\n";
print $fh "    mux_8to2_" . $bitwidth . "bit u_eight_two_mux(\n";
print $fh "      .mask(mask[eight_two_i*8 +: 8]),\n";
print $fh "      .data(data[eight_two_i*" . $bitwidth * 8 . " +: " . $bitwidth * 8 . "]),\n";
print $fh "      .out(result_eight_two[eight_two_i*" . $bitwidth * 2 . " +: " . $bitwidth * 2 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar eight_four_i;\n";
print $fh "generate\n";
print $fh "  for (eight_four_i = 0; eight_four_i < ". int($p/4) ."; eight_four_i = eight_four_i + 1) begin : eight_four_mux\n";
print $fh "    mux_8to4_" . $bitwidth . "bit u_eight_four_mux(\n";
print $fh "      .mask(mask[eight_four_i*8 +: 8]),\n";
print $fh "      .data(data[eight_four_i*" . $bitwidth * 8 . " +: " . $bitwidth * 8 . "]),\n";
print $fh "      .out(result_eight_four[eight_four_i*" . $bitwidth * 4 . " +: " . $bitwidth * 4 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar sixteen_two_i;\n";
print $fh "generate\n";
print $fh "  for (sixteen_two_i = 0; sixteen_two_i < ". int($p/2) ."; sixteen_two_i = sixteen_two_i + 1) begin : sixteen_two_mux\n";
print $fh "    mux_16to2_" . $bitwidth . "bit u_sixteen_two_mux(\n";
print $fh "      .mask(mask[sixteen_two_i*16 +: 16]),\n";
print $fh "      .data(data[sixteen_two_i*" . $bitwidth * 16 . " +: " . $bitwidth * 16 . "]),\n";
print $fh "      .out(result_sixteen_two[sixteen_two_i*" . $bitwidth * 2 . " +: " . $bitwidth * 2 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar sixteen_four_i;\n";
print $fh "generate\n";
print $fh "  for (sixteen_four_i = 0; sixteen_four_i < ". int($p/4) ."; sixteen_four_i = sixteen_four_i + 1) begin : sixteen_four_mux\n";
print $fh "    mux_16to4_" . $bitwidth . "bit u_sixteen_four_mux(\n";
print $fh "      .mask(mask[sixteen_four_i*16 +: 16]),\n";
print $fh "      .data(data[sixteen_four_i*" . $bitwidth * 16 . " +: " . $bitwidth * 16 . "]),\n";
print $fh "      .out(result_sixteen_four[sixteen_four_i*" . $bitwidth * 4 . " +: " . $bitwidth * 4 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar sixteen_eight_i;\n";
print $fh "generate\n";
print $fh "  for (sixteen_eight_i = 0; sixteen_eight_i < ". int($p/8) ."; sixteen_eight_i = sixteen_eight_i + 1) begin : sixteen_eight_mux\n";
print $fh "    mux_16to8_" . $bitwidth . "bit u_sixteen_eight_mux(\n";
print $fh "      .mask(mask[sixteen_eight_i*16 +: 16]),\n";
print $fh "      .data(data[sixteen_eight_i*" . $bitwidth * 16 . " +: " . $bitwidth * 16 . "]),\n";
print $fh "      .out(result_sixteen_eight[sixteen_eight_i*" . $bitwidth * 8 . " +: " . $bitwidth * 8 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar thridtytwo_four_i;\n";
print $fh "generate\n";
print $fh "  for (thridtytwo_four_i = 0; thridtytwo_four_i < ". int($p/4) ."; thridtytwo_four_i = thridtytwo_four_i + 1) begin : thridtytwo_four_mux\n";
print $fh "    mux_32to4_" . $bitwidth . "bit u_thridtytwo_four_mux(\n";
print $fh "      .mask(mask[thridtytwo_four_i*32 +: 32]),\n";
print $fh "      .data(data[thridtytwo_four_i*" . $bitwidth * 32 . " +: " . $bitwidth * 32 . "]),\n";
print $fh "      .out(result_thridtytwo_four[thridtytwo_four_i*" . $bitwidth * 4 . " +: " . $bitwidth * 4 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar thridtytwo_eight_i;\n";
print $fh "generate\n";
print $fh "  for (thridtytwo_eight_i = 0; thridtytwo_eight_i < ". int($p/8) ."; thridtytwo_eight_i = thridtytwo_eight_i + 1) begin : thridtytwo_eight_mux\n";
print $fh "    mux_32to8_" . $bitwidth . "bit u_thridtytwo_eight_mux(\n";
print $fh "      .mask(mask[thridtytwo_eight_i*32 +: 32]),\n";
print $fh "      .data(data[thridtytwo_eight_i*" . $bitwidth * 32 . " +: " . $bitwidth * 32 . "]),\n";
print $fh "      .out(result_thridtytwo_eight[thridtytwo_eight_i*" . $bitwidth * 8 . " +: " . $bitwidth * 8 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "genvar thridtytwo_sixteen_i;\n";
print $fh "generate\n";
print $fh "  for (thridtytwo_sixteen_i = 0; thridtytwo_sixteen_i < ". int($p/16) ."; thridtytwo_sixteen_i = thridtytwo_sixteen_i + 1) begin : thridtytwo_sixteen_mux\n";
print $fh "    mux_32to16_" . $bitwidth . "bit u_thridtytwo_sixteen_mux(\n";
print $fh "      .mask(mask[thridtytwo_sixteen_i*32 +: 32]),\n";
print $fh "      .data(data[thridtytwo_sixteen_i*" . $bitwidth * 32 . " +: " . $bitwidth * 32 . "]),\n";
print $fh "      .out(result_thridtytwo_sixteen[thridtytwo_sixteen_i*" . $bitwidth * 16 . " +: " . $bitwidth * 16 . "])\n";
print $fh "    );\n";
print $fh "  end\n";
print $fh "endgenerate\n";
print $fh "\n";
print $fh "always @(*) begin\n";
print $fh "  case(mode[3:2])\n";
print $fh "    2'b00: out = data[" . ($p * $bitwidth - 1) . ":0];\n";
print $fh "    2'b01: begin\n";
print $fh "      case(mode[1:0])\n";
print $fh "        2'b00: out = result_four_two;\n";
print $fh "        2'b01: out = result_eight_four;\n";
print $fh "        2'b10: out = result_sixteen_eight;\n";
print $fh "        2'b11: out = result_thridtytwo_sixteen;\n";
print $fh "        default: out = " . $p * $bitwidth . "'b0;\n";
print $fh "      endcase\n";
print $fh "    end\n";
print $fh "    2'b10: begin\n";
print $fh "      case(mode[1:0])\n";
print $fh "        2'b00: out = result_four_one;\n";
print $fh "        2'b01: out = result_eight_two;\n";
print $fh "        2'b10: out = result_sixteen_four;\n";
print $fh "        2'b11: out = result_thridtytwo_eight;\n";
print $fh "        default: out = " . $p * $bitwidth . "'b0;\n";
print $fh "      endcase\n";
print $fh "    end\n";
print $fh "    2'b11: begin\n";
print $fh "      case(mode[1:0])\n";
print $fh "        2'b00: out = " . $p * $bitwidth . "'b0;\n";
print $fh "        2'b01: out = result_eight_one;\n";
print $fh "        2'b10: out = result_sixteen_two;\n";
print $fh "        2'b11: out = result_thridtytwo_four;\n";
print $fh "        default: out = " . $p * $bitwidth . "'b0;\n";
print $fh "      endcase\n";
print $fh "    end\n";
print $fh "    default: out = " . $p * $bitwidth . "'b0;\n";
print $fh "  endcase\n";
print $fh "end\n";
print $fh "\n";
print $fh "endmodule\n";