import torch
import numpy as np
import sys
import os
import time # Import time module
import argparse # Import argparse module
import json # Import json module

# Add common_utils to Python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../common_utils')))
# Now using load_tensor_from_bin and save_tensor_to_bin
from data_gen import load_tensor_from_bin, save_tensor_to_bin, generate_random_tensor

def gemm_pytorch_fp16(ifmap_np: np.ndarray, weight_np: np.ndarray) -> np.ndarray:
    """
    Performs GEMM operation using PyTorch with FP16 precision.
    Input shapes: ifmap_np (M, K), weight_np (K, N) for A@B matmul
    Output shape: (M, N)
    """
    ifmap_torch = torch.from_numpy(ifmap_np.copy()).half() # Use .copy() to avoid potential negative stride issues with torch
    weight_torch = torch.from_numpy(weight_np.copy()).half()
    
    if ifmap_np.shape[1] != weight_np.shape[0]:
        raise ValueError(f"K dimension mismatch: ifmap {ifmap_np.shape} vs weight {weight_np.shape}. Expecting (M,K) and (K,N).")

    start_time = time.perf_counter()
    output_torch = torch.matmul(ifmap_torch, weight_torch)
    end_time = time.perf_counter()
    execution_time = end_time - start_time
    print(f"PyTorch FP16 GEMM execution time: {execution_time:.6f} seconds")
    return output_torch.cpu().numpy(), execution_time

def main():
    parser = argparse.ArgumentParser(description="PyTorch GEMM Reference Script")
    parser.add_argument("--M", type=int, required=True, help="M dimension of ifmap (rows)")
    parser.add_argument("--K", type=int, required=True, help="K dimension of ifmap (cols) and weight (rows)")
    parser.add_argument("--N", type=int, required=True, help="N dimension of weight (cols)")
    parser.add_argument("--ifmap_path", type=str, required=True, help="Path to the input ifmap .bin file")
    parser.add_argument("--weight_path", type=str, required=True, help="Path to the input weight .bin file")
    parser.add_argument("--output_path_fp16", type=str, help="Path to save the FP16 GEMM output .bin file")
    parser.add_argument("--precision", type=str, choices=['fp16'], default='fp16', help="Precision to run: fp16. Note: Script currently only robustly supports fp16 output and metrics for fp16.")
    parser.add_argument("--output_performance_json", type=str, help="Path to save the performance metrics JSON file.")

    args = parser.parse_args()

    if args.precision == 'fp16' and not args.output_path_fp16:
        parser.error("--output_path_fp16 is required when precision is 'fp16'")

    M, K_gemm, N_gemm = args.M, args.K, args.N
    gemm_ifmap_shape = (M, K_gemm)
    gemm_weight_shape = (K_gemm, N_gemm)
    # Data type is typically FP16 for GEMM, but can be loaded as specified by source or converted
    # For this script, we assume the input .bin files are FP16 as generated by data_gen.py default for GEMM.
    # The gemm_pytorch_fp32 function will handle conversion from FP16 numpy array to FP32 tensor.
    ifmap_dtype_load = np.float16
    weight_dtype_load = np.float16 

    print(f"Loading ifmap from: {args.ifmap_path}")
    ifmap_data = load_tensor_from_bin(args.ifmap_path, dtype=ifmap_dtype_load, shape=gemm_ifmap_shape)
    print(f"Loading weight from: {args.weight_path}")
    weight_data = load_tensor_from_bin(args.weight_path, dtype=weight_dtype_load, shape=gemm_weight_shape)

    print(f"Loaded ifmap shape: {ifmap_data.shape}, dtype: {ifmap_data.dtype}")
    print(f"Loaded weight shape: {weight_data.shape}, dtype: {weight_data.dtype}")

    if args.precision in ['fp16']:
        print("\nRunning FP16 GEMM...")
        output_pytorch_fp16, exec_time_fp16 = gemm_pytorch_fp16(ifmap_data, weight_data)
        print(f"PyTorch FP16 GEMM output shape: {output_pytorch_fp16.shape}, dtype: {output_pytorch_fp16.dtype}")
        print(f"Saving FP16 GEMM output to: {args.output_path_fp16}")
        save_tensor_to_bin(output_pytorch_fp16, args.output_path_fp16)
        print("FP16 GEMM output saved.")

        if args.output_performance_json:
            m_val, k_val, n_val = args.M, args.K, args.N
            flops = 2 * m_val * k_val * n_val
            gops = (flops / exec_time_fp16) / 1e9 if exec_time_fp16 > 0 else 0
            performance_data = {
                "op_type": "gemm",
                "precision": "fp16",
                "dimensions": {"M": m_val, "K": k_val, "N": n_val},
                "device": "cpu",
                "latency_ms": exec_time_fp16 * 1000,
                "throughput": gops,
                "throughput_unit": "GOPS"
            }
            with open(args.output_performance_json, 'w') as f:
                json.dump(performance_data, f, indent=4)
            print(f"Performance JSON saved to: {args.output_performance_json}")

    print("\nGEMM PyTorch reference script finished.")

if __name__ == '__main__':
    main() 